"""
Tests for test.sh generator module.

Tests the test.sh generation functionality including header comment addition.
"""

from crsbench.migration.test_sh import add_generation_header as _add_generation_header


class TestAddGenerationHeader:
    """Tests for _add_generation_header function."""

    def test_adds_header_with_shebang(self):
        """Test that header is added correctly with shebang."""
        original = "#!/bin/bash\necho 'test'"
        result = _add_generation_header(original, "test-benchmark")

        # Check shebang is present once
        assert result.startswith("#!/bin/bash\n")
        assert result.count("#!/bin/bash") == 1

        # Check header comments are present
        assert "Auto-generated test.sh for CRSBench benchmark" in result
        assert "Generated by: Claude Agent SDK" in result
        assert "Benchmark: test-benchmark" in result
        assert "Method: two-phase analysis" in result

        # Check original content is preserved
        assert "echo 'test'" in result

    def test_adds_header_without_shebang(self):
        """Test that header is added when original has no shebang."""
        original = "echo 'test'"
        result = _add_generation_header(original, "test-benchmark")

        # Check shebang is added
        assert result.startswith("#!/bin/bash\n")

        # Check header comments are present
        assert "Auto-generated test.sh" in result
        assert "Benchmark: test-benchmark" in result

        # Check original content is preserved
        assert "echo 'test'" in result

    def test_docker_testing_method_in_header(self):
        """Test that Docker testing method is reflected in header."""
        original = "#!/bin/bash\necho 'test'"
        result = _add_generation_header(
            original, "test-benchmark", with_docker_testing=True
        )

        # Check Docker testing method is mentioned
        assert "Method: iterative Docker testing (MCP-enhanced)" in result

    def test_two_phase_method_in_header(self):
        """Test that two-phase method is reflected in header."""
        original = "#!/bin/bash\necho 'test'"
        result = _add_generation_header(
            original, "test-benchmark", with_docker_testing=False
        )

        # Check two-phase method is mentioned
        assert "Method: two-phase analysis" in result

    def test_preserves_complex_script(self):
        """Test that complex scripts are preserved correctly."""
        original = """#!/bin/bash
set -e

# Build configuration
if [ -z "${MVN}" ]; then
    MVN=mvn
fi

# Run tests
${MVN} test -Drat.skip=true

exit $?
"""
        result = _add_generation_header(original, "complex-benchmark")

        # Check all content is preserved
        assert "set -e" in result
        assert "Build configuration" in result
        assert "if [ -z" in result
        assert "${MVN} test" in result
        assert "exit $?" in result

        # Check header is present
        assert "Auto-generated test.sh" in result
        assert "complex-benchmark" in result

    def test_timestamp_format(self):
        """Test that timestamp is in correct format."""
        original = "#!/bin/bash\necho 'test'"
        result = _add_generation_header(original, "test-benchmark")

        # Check timestamp line exists
        assert "Generated at:" in result

        # Extract timestamp line
        for line in result.split("\n"):
            if "Generated at:" in line:
                # Should contain a valid timestamp (just check format exists)
                assert len(line.split(":")) >= 3  # HH:MM:SS

    def test_analysis_reference(self):
        """Test that analysis file reference is included."""
        original = "#!/bin/bash\necho 'test'"
        result = _add_generation_header(original, "test-benchmark")

        # Check reference to analysis file
        assert "test_analysis.md" in result
        assert ".aixcc/test_analysis.md" in result

    def test_handles_empty_script(self):
        """Test handling of empty or minimal scripts."""
        original = "#!/bin/bash\n"
        result = _add_generation_header(original, "minimal-benchmark")

        # Should still have header
        assert "Auto-generated test.sh" in result
        assert "minimal-benchmark" in result
        assert result.startswith("#!/bin/bash\n")

    def test_removes_duplicate_shebang(self):
        """Test that duplicate shebang is removed."""
        original = "#!/bin/bash\n#!/bin/bash\necho 'test'"
        result = _add_generation_header(original, "test-benchmark")

        # Should only have one shebang (from header)
        assert result.count("#!/bin/bash") == 1

        # Content should still be there
        assert "echo 'test'" in result

    def test_multiline_commands_preserved(self):
        """Test that multiline commands are preserved correctly."""
        original = """#!/bin/bash
if [ -z "${MVN}" ]; then
    MVN=mvn
fi

${MVN} test \\
    -Drat.skip=true \\
    -Dcheckstyle.skip=true
"""
        result = _add_generation_header(original, "multiline-benchmark")

        # Check multiline command is preserved
        assert "-Drat.skip=true \\" in result
        assert "-Dcheckstyle.skip=true" in result
