"""
Utility functions for test.sh generation.

This module contains helper functions for copying benchmark files,
adding generation headers, and the main entry point for benchmark processing.
"""

import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

from crsbench.utils.logger import get_logger

logger = get_logger(__name__)


def copy_benchmark_files_to_project(
    benchmark_dir: str, project_dir: str, *, verbose: bool = False
) -> Optional[str]:
    """
    Copy benchmark's OSS-Fuzz files to project/.oss-fuzz directory.

    This helps the agent understand the build environment and dependencies
    by providing access to build.sh, Dockerfile, harness files, etc.

    Args:
        benchmark_dir: Path to benchmark directory (contains build.sh, Dockerfile, etc.)
        project_dir: Path to project source repository
        verbose: Enable verbose logging

    Returns:
        Path to .oss-fuzz directory in project, or None if copy failed
    """
    project_path = Path(project_dir)
    benchmark_path = Path(benchmark_dir)
    oss_fuzz_path = project_path / ".oss-fuzz"

    try:
        # Create .oss-fuzz directory
        oss_fuzz_path.mkdir(parents=True, exist_ok=True)

        # Files to copy from benchmark directory
        files_to_copy = [
            "build.sh",
            "Dockerfile",
            "project.yaml",
        ]

        # Copy files
        copied_files = []
        for filename in files_to_copy:
            src = benchmark_path / filename
            dst = oss_fuzz_path / filename

            if src.exists():
                shutil.copy2(src, dst)
                copied_files.append(filename)
                if verbose:
                    logger.debug(f"Copied {filename} to .oss-fuzz/")

        # Copy .aixcc directory (contains harness files metadata)
        aixcc_src = benchmark_path / ".aixcc"
        aixcc_dst = oss_fuzz_path / ".aixcc"

        if aixcc_src.exists():
            if aixcc_dst.exists():
                shutil.rmtree(aixcc_dst)
            shutil.copytree(aixcc_src, aixcc_dst)
            copied_files.append(".aixcc/")
            if verbose:
                logger.debug("Copied .aixcc/ to .oss-fuzz/")

        if verbose and copied_files:
            logger.debug(f"Copied OSS-Fuzz files to {oss_fuzz_path}")

        return str(oss_fuzz_path)

    except Exception as e:
        if verbose:
            logger.warning(f"Failed to copy benchmark files: {e}")
        return None


def add_generation_header(
    script_content: str, benchmark_name: str, *, with_docker_testing: bool = False
) -> str:
    """
    Add generation header comment to test.sh script.

    Args:
        script_content: Original test.sh script content
        benchmark_name: Name of the benchmark
        with_docker_testing: Whether Docker testing was used

    Returns:
        Script content with header comment added
    """
    # Generate timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Determine generation method
    method = (
        "iterative Docker testing (MCP-enhanced)"
        if with_docker_testing
        else "two-phase analysis"
    )

    # Create header comment
    header = f"""#!/bin/bash
#
# Auto-generated test.sh for CRSBench benchmark
#
# Generated by: Claude Agent SDK (test.sh generator)
# Benchmark: {benchmark_name}
# Method: {method}
# Generated at: {timestamp}
#
# This script runs functional/unit tests for the project.
# For analysis details, see .aixcc/test_analysis.md
#

"""

    # Remove all shebangs from the beginning of the script
    while script_content.startswith("#!/"):
        first_newline = script_content.find("\n")
        if first_newline != -1:
            script_content = script_content[first_newline + 1 :].lstrip("\n")
        else:
            # Single line with only shebang
            script_content = ""
            break

    # Combine header with script content
    return header + script_content


def generate_test_sh_for_benchmark(
    benchmark_name: str,
    benchmark_dir: str,
    project_dir: str,
    output_path: Optional[str] = None,
    litellm_base_url: Optional[str] = None,
    litellm_api_key: Optional[str] = None,
    model: str = "claude-sonnet-4-5-20250929",
    *,
    with_docker_testing: bool = True,
    verbose: bool = False,
) -> Dict[str, Any]:
    """
    Generate test.sh and bad_patch.diff for a benchmark.

    Args:
        benchmark_name: Name of the benchmark
        benchmark_dir: Path to benchmark directory (contains .aixcc/)
        project_dir: Path to project source repository
        output_path: Optional custom output path for test.sh
        litellm_base_url: Optional LiteLLM proxy URL
        litellm_api_key: Optional LiteLLM API key
        model: Model to use (default: claude-sonnet-4-5-20250929)
        with_docker_testing: Enable iterative Docker testing via MCP (default: True)
        verbose: Enable verbose logging

    Returns:
        Dictionary with generation results:
        {
            "success": bool,
            "test_sh_path": str,               # benchmarks/<name>/test.sh
            "bad_patch_path": str,             # benchmarks/<name>/bad_patch.diff
            "analysis_md_path": str,           # .agent/test_analysis.md
            "rationale_md_path": str,          # .agent/test_sh_rationale.md
            "agent_log_path": str,             # .agent/agent_log.txt
            "execution_log_path": str,         # .agent/test_sh_execution.log
            "test_sh_executed": bool,          # Whether test.sh ran successfully
            "message": str
        }
    """
    # Import here to avoid circular imports
    from crsbench.migration.test_sh.generator import ShTestGenerator

    benchmark_path = Path(benchmark_dir)
    project_path = Path(project_dir)

    if not benchmark_path.is_dir():
        return {
            "success": False,
            "message": f"Benchmark directory not found: {benchmark_dir}",
        }

    if not project_path.is_dir():
        return {
            "success": False,
            "message": f"Project directory not found: {project_dir}",
        }

    # Check if test.sh already exists
    default_test_sh_path = benchmark_path / "test.sh"
    if output_path is None:
        output_path = str(default_test_sh_path)

    output_file = Path(output_path)
    if output_file.exists() and not verbose:
        return {
            "success": False,
            "message": f"test.sh already exists at {output_path}. Use --force to overwrite.",
        }

    # Create generator
    generator = ShTestGenerator(
        litellm_base_url=litellm_base_url, litellm_api_key=litellm_api_key, model=model
    )

    # Step 0: Copy benchmark OSS-Fuzz files to project directory
    if verbose:
        logger.debug(f"Copying OSS-Fuzz files to {project_dir}/.oss-fuzz/...")

    copy_benchmark_files_to_project(benchmark_dir, project_dir, verbose=verbose)

    # Step 1: Find unit tests
    if verbose:
        logger.debug(f"Analyzing unit tests in {project_dir}...")

    test_analysis_md, analysis_log = generator.find_unit_tests_sync(
        project_dir, benchmark_dir, verbose=verbose
    )

    # Save analysis markdown to .agent directory
    # Only write if agent didn't already create it via skill
    agent_dir = benchmark_path / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)

    analysis_md_path = agent_dir / "test_analysis.md"
    if analysis_md_path.exists():
        if verbose:
            logger.debug(f"Agent already created analysis at {analysis_md_path}")
    else:
        # Fallback: save extracted response if agent didn't create the file
        with analysis_md_path.open("w") as f:
            f.write(test_analysis_md)
        if verbose:
            logger.debug(f"Test analysis saved to {analysis_md_path}")

    # Step 2: Generate test.sh and bad_patch.diff (integrated in same agent)
    if verbose:
        mode_msg = "with Docker testing" if with_docker_testing else "two-phase"
        logger.debug(f"Generating test.sh and bad_patch.diff ({mode_msg})...")

    test_sh_content, agent_response_text, generation_log = (
        generator.generate_test_sh_script_sync(
            test_analysis_md,
            benchmark_name,
            benchmark_dir,
            with_docker_testing=with_docker_testing,
            verbose=verbose,
        )
    )

    # Save agent response (rationale) to .agent/test_sh_rationale.md
    # Only write if agent didn't already create it via skill
    rationale_md_path = agent_dir / "test_sh_rationale.md"
    if rationale_md_path.exists():
        if verbose:
            logger.debug(f"Agent already created rationale at {rationale_md_path}")
    else:
        # Fallback: save extracted response if agent didn't create the file
        with rationale_md_path.open("w") as f:
            f.write(f"""# test.sh Generation Rationale

Generated: {datetime.now().isoformat()}
Benchmark: {benchmark_name}
Method: {"iterative Docker testing (MCP-enhanced)" if with_docker_testing else "two-phase analysis"}

## Agent Response

{agent_response_text}
""")
        if verbose:
            logger.debug(f"Agent response saved to {rationale_md_path}")

    # Verify bad_patch.diff was created by agent
    bad_patch_path = benchmark_path / "bad_patch.diff"
    if not bad_patch_path.exists():
        if verbose:
            logger.warning(f"bad_patch.diff not found at {bad_patch_path}")
            logger.warning("Agent may have failed to generate bad_patch.diff")
    else:
        if verbose:
            logger.debug(f"bad_patch.diff created by agent at {bad_patch_path}")

    # Save test.sh only if NOT using Docker testing
    # (Docker testing mode: agent already created test.sh using Write/Edit tools)
    if not with_docker_testing:
        # Add header comment to test.sh
        test_sh_content = add_generation_header(
            test_sh_content, benchmark_name, with_docker_testing=with_docker_testing
        )

        # Save test.sh
        with output_file.open("w") as f:
            f.write(test_sh_content)

        # Make executable
        output_file.chmod(0o755)

        if verbose:
            logger.debug(f"test.sh generated at {output_path}")
    else:
        # Docker testing mode: test.sh already exists (created by agent)
        if verbose:
            logger.debug(
                f"test.sh already created by agent during Docker testing at {output_path}"
            )

        # Verify test.sh exists
        if not output_file.exists():
            if verbose:
                logger.warning(
                    f"test.sh not found at {output_path}, saving extracted script"
                )
            # Fallback: save extracted script
            test_sh_content = add_generation_header(
                test_sh_content, benchmark_name, with_docker_testing=with_docker_testing
            )
            with output_file.open("w") as f:
                f.write(test_sh_content)
            output_file.chmod(0o755)

    # Step 3: Save combined agent log to .agent directory
    agent_log_path = agent_dir / "agent_log.txt"

    # Delete existing agent_log.txt if it exists
    if agent_log_path.exists():
        agent_log_path.unlink()
        if verbose:
            logger.debug("Removed existing agent_log.txt")

    # Determine generation method
    method_description = (
        "Phase 1: Unit test discovery using Claude Agent SDK\n"
        "Phase 2: Test.sh and bad_patch.diff generation (integrated) "
    )
    if with_docker_testing:
        method_description += "with MCP-enhanced Docker testing (iterative refinement)"
    else:
        method_description += "using two-phase analysis (no Docker testing)"

    combined_log = f"""# Test.sh and Bad Patch Generation Agent Log
Generated: {datetime.now().isoformat()}
Benchmark: {benchmark_name}
Project Directory: {project_dir}
Method: {method_description}

{analysis_log}
{generation_log}
"""
    with agent_log_path.open("w") as f:
        f.write(combined_log)

    if verbose:
        logger.debug(f"Agent log saved to {agent_log_path}")

    # Step 4: Execute test.sh and save output
    if verbose:
        logger.debug("Executing test.sh to verify functionality...")

    execution_log_path = agent_dir / "test_sh_execution.log"
    execution_success = False
    execution_output = ""

    try:
        # Use shared run_helper for test.sh execution
        from crsbench.utils.run_helper import run_test_sh

        # Run test.sh
        test_result = run_test_sh(
            benchmark=benchmark_name,
            expect_success=True,
            raise_exception=False,
        )
        execution_success = test_result.success
        execution_output = test_result.stdout + test_result.stderr

        # Save execution output
        with execution_log_path.open("w") as f:
            f.write(f"""# test.sh Execution Log

Executed: {datetime.now().isoformat()}
Benchmark: {benchmark_name}
Status: {"Success" if execution_success else "Failed"}
Return Code: {test_result.returncode}
Exit Code Type: {test_result.exit_code_type.name if test_result.exit_code_type else "Unknown"}

## Output

{execution_output}
""")

        if verbose:
            if execution_success:
                logger.debug("test.sh executed successfully")
            else:
                logger.warning(
                    f"test.sh execution had issues (see {execution_log_path})"
                )
            logger.debug(f"Execution log saved to {execution_log_path}")

    except Exception as e:
        execution_output = f"Error executing test.sh: {str(e)}"
        execution_success = False

        # Save error log
        with execution_log_path.open("w") as f:
            f.write(f"""# test.sh Execution Log

Executed: {datetime.now().isoformat()}
Benchmark: {benchmark_name}
Status: Execution Failed

## Error

{execution_output}
""")

        if verbose:
            logger.error(f"Failed to execute test.sh: {e}")
            logger.debug(f"Error log saved to {execution_log_path}")

    return {
        "success": True,
        "test_sh_path": output_path,
        "bad_patch_path": str(bad_patch_path),
        "analysis_md_path": str(analysis_md_path),
        "rationale_md_path": str(rationale_md_path),
        "agent_log_path": str(agent_log_path),
        "execution_log_path": str(execution_log_path),
        "test_sh_executed": execution_success,
        "message": f"Successfully generated test.sh and bad_patch.diff for {benchmark_name}",
    }


# Backward compatibility alias
_copy_benchmark_files_to_project = copy_benchmark_files_to_project
_add_generation_header = add_generation_header
