#!/bin/bash
# Unified integration test script for patch CRS (bug-fixing type)
#
# Usage:
#   ./run_local_test-patch.sh [OPTIONS]
#
# Options:
#   -c, --crs <name>        CRS name (default: vincent)
#   -b, --benchmark <name>  Benchmark name (default: afc-libexif-delta-01)
#   -t, --timeout <secs>    Max total time in seconds (default: 600)
#   --trials <n>            Number of trials (default: 1)
#   --skip-cleanup          Don't delete generated config file after test
#   -h, --help              Show this help message
#
# Examples:
#   ./run_local_test-patch.sh
#   ./run_local_test-patch.sh -c prism -b atlanta-nasm-delta-01
#   ./run_local_test-patch.sh --crs claude-code --benchmark afc-libexif-delta-01 --timeout 1200

set -e  # Exit on error

# Default values
CRS_NAME="vincent"
BENCHMARK="afc-libexif-delta-01"
MAX_TOTAL_TIME=3000  # Must be > build_timeout + run_timeout + verify_timeout
TRIALS=1
SKIP_CLEANUP=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -c|--crs)
            CRS_NAME="$2"
            shift 2
            ;;
        -b|--benchmark)
            BENCHMARK="$2"
            shift 2
            ;;
        -t|--timeout)
            MAX_TOTAL_TIME="$2"
            shift 2
            ;;
        --trials)
            TRIALS="$2"
            shift 2
            ;;
        --skip-cleanup)
            SKIP_CLEANUP=true
            shift
            ;;
        -h|--help)
            sed -n '2,18p' "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Determine full CRS name (add atlantis- prefix if not present)
if [[ ! "$CRS_NAME" =~ ^atlantis- ]]; then
    FULL_CRS_NAME="atlantis-$CRS_NAME"
else
    FULL_CRS_NAME="$CRS_NAME"
    CRS_NAME="${CRS_NAME#atlantis-}"
fi

# Configuration
EXPERIMENT_NAME="integration-test-patch-$CRS_NAME"
CONFIG_DIR="$SCRIPT_DIR/.generated-configs"
CONFIG_FILE="$CONFIG_DIR/test-experiment-config-patch-$CRS_NAME.yaml"

# Path overrides (environment variables or defaults)
OSS_FUZZ_PATH="${OSS_FUZZ_PATH:-$PROJECT_ROOT/oss-fuzz}"
REGISTRY_DIR="${REGISTRY_DIR:-$PROJECT_ROOT/crses/registry}"
CRS_CONFIGS_DIR="${CRS_CONFIGS_DIR:-$PROJECT_ROOT/crses/configs}"
BENCHMARKS_ROOT="${BENCHMARKS_ROOT:-$PROJECT_ROOT/benchmarks}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== CRSBench Patch CRS Integration Test ===${NC}"
echo ""

echo -e "${GREEN}Configuration:${NC}"
echo "  CRS: $FULL_CRS_NAME"
echo "  Benchmark: $BENCHMARK"
echo "  Experiment name: $EXPERIMENT_NAME"
echo "  Max total time: ${MAX_TOTAL_TIME}s"
echo "  Trials: $TRIALS"
echo "  Mode: Local (no distributed execution)"
echo "  OSS-Fuzz path: $OSS_FUZZ_PATH"
echo "  Registry directory: $REGISTRY_DIR"
echo "  CRS configs directory: $CRS_CONFIGS_DIR"
echo "  Benchmarks root: $BENCHMARKS_ROOT"
echo ""

# Create config directory if it doesn't exist
mkdir -p "$CONFIG_DIR"

# Generate config file
echo -e "${YELLOW}Generating config file: $CONFIG_FILE${NC}"
cat > "$CONFIG_FILE" << EOF
# Auto-generated test configuration for patch CRS integration tests
# Generated by: run_local_test-patch.sh
# CRS: $FULL_CRS_NAME
# Benchmark: $BENCHMARK

experiment: "$EXPERIMENT_NAME"
description: "Integration test configuration for $FULL_CRS_NAME patch generation CRS"

# Execution Configuration
trials: $TRIALS
mode: full
max_total_time: $MAX_TOTAL_TIME

# CRS Selection
crses:
  - $FULL_CRS_NAME

# Benchmark Selection
benchmarks:
  - $BENCHMARK

# Difficulty Control
difficulty_level: 1

# Monitoring & Snapshots
snapshot_period: 60

# Storage Configuration
experiment_filestore: /tmp/crsbench/crsbench-$EXPERIMENT_NAME/experiment-data
report_filestore: /tmp/crsbench/crsbench-$EXPERIMENT_NAME/report-data

# LiteLLM Configuration
litellm_mode: passthrough

# Build Configuration
build_timeout: 1200   # 20 minutes for patch CRS build
run_timeout: 1200     # 20 minutes for patch generation
verify_timeout: 600   # 10 minutes for patch verification

# Hints Configuration
hints_enabled: false

# Reproducibility
git_hash: null
EOF

echo ""

# Set up virtual environment
echo -e "${YELLOW}Setting up virtual environment...${NC}"
cd "$PROJECT_ROOT"
if [ ! -d ".venv" ]; then
    echo "Creating new virtual environment..."
    uv sync
else
    echo "Virtual environment exists, syncing dependencies..."
    uv sync
fi
echo ""

# Clean up previous test data
echo -e "${YELLOW}Cleaning up previous test data...${NC}"
TEST_DIR="/tmp/crsbench-$EXPERIMENT_NAME/"
if [ -n "$TEST_DIR" ] && [ -d "$TEST_DIR" ]; then
    rm -rf "$TEST_DIR"
fi

# Activate virtual environment
echo -e "${YELLOW}Activating virtual environment...${NC}"
source "$PROJECT_ROOT/.venv/bin/activate"
echo ""

# Cleanup function
cleanup() {
    if [ "$SKIP_CLEANUP" = false ]; then
        echo -e "${YELLOW}Cleaning up generated config file...${NC}"
        rm -f "$CONFIG_FILE"
        # Remove config dir if empty
        rmdir "$CONFIG_DIR" 2>/dev/null || true
    else
        echo -e "${YELLOW}Skipping config cleanup (--skip-cleanup specified)${NC}"
        echo "  Config file: $CONFIG_FILE"
    fi
}

# Set up trap for cleanup
trap cleanup EXIT

# Run the experiment
echo -e "${GREEN}Running CRSBench patch CRS experiment...${NC}"
echo ""

crsbench \
   --experiment-config "$CONFIG_FILE" \
   --experiment-name "$EXPERIMENT_NAME" \
   --benchmarks "$BENCHMARK" \
   --crses "$FULL_CRS_NAME" \
   --oss-fuzz-path "$OSS_FUZZ_PATH" \
   --registry-dir "$REGISTRY_DIR" \
   --crs-configs-dir "$CRS_CONFIGS_DIR" \
   --benchmarks-root "$BENCHMARKS_ROOT" \
   --debug

# Check exit status
if [ $? -eq 0 ]; then
    echo ""
    echo -e "${GREEN}=== Integration test completed successfully ===${NC}"
    echo ""
    echo "Results stored in:"
    echo "  Experiment data: /tmp/crsbench-$EXPERIMENT_NAME/experiment-data"
    echo "  Reports: /tmp/crsbench-$EXPERIMENT_NAME/report-data"

    # Show directory structure (exclude crs-build and crs-input which are large)
    echo ""
    echo "Directory structure:"
    [ -d /tmp/crsbench-$EXPERIMENT_NAME/ ] && tree -L 12 -I 'crs-build|crs-input|snapshot*' /tmp/crsbench-$EXPERIMENT_NAME/

    exit 0
else
    echo ""
    echo -e "${RED}=== Integration test failed ===${NC}"

    # Show directory structure (exclude crs-build and crs-input which are large)
    echo ""
    echo "Directory structure:"
    [ -d /tmp/crsbench-$EXPERIMENT_NAME/ ] && tree -L 12 -I 'crs-build|crs-input|snapshot*' /tmp/crsbench-$EXPERIMENT_NAME/

    exit 1
fi
