#!/usr/bin/env python3
"""
Sync LiteLLM Models from Upstream

This script fetches available models from an upstream LiteLLM instance
and updates the local default-models.yaml configuration.

The script automatically loads environment variables from .env file.

Usage:
    python scripts/sync-upstream-models.py --upstream-url http://central-litellm:4000 --api-key sk-...
    python scripts/sync-upstream-models.py  # Uses env vars from .env file or environment
"""

import argparse
import os
import sys
from pathlib import Path

import requests
import yaml
from dotenv import load_dotenv

# Project root
PROJECT_ROOT = Path(__file__).parent.parent
DEFAULT_MODELS_PATH = PROJECT_ROOT / "services" / "litellm" / "default-models.yaml"

# Load environment variables from .env file
load_dotenv(PROJECT_ROOT / ".env")


def fetch_upstream_models(base_url: str, api_key: str) -> list[dict]:
    """Fetch available models from upstream LiteLLM instance.

    Args:
        base_url: Upstream LiteLLM base URL (e.g., http://central-litellm:4000)
        api_key: API key for authentication

    Returns:
        List of model dictionaries with 'id' field

    Raises:
        requests.RequestException: If request fails
    """
    url = f"{base_url.rstrip('/')}/models"
    headers = {"Authorization": f"Bearer {api_key}"}

    print(f"Fetching models from {url}...")
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()

    data = response.json()
    models = data.get("data", [])

    print(f"Found {len(models)} models from upstream")
    return models


def generate_proxy_config(upstream_url: str, models: list[dict]) -> dict:
    """Generate proxy mode configuration for upstream models.

    Args:
        upstream_url: Upstream LiteLLM base URL
        models: List of model dictionaries from upstream

    Returns:
        Configuration dictionary with model_list and litellm_settings
    """
    model_list = []

    for model in models:
        model_name = model.get("id")
        if not model_name:
            continue

        model_list.append({
            "model_name": model_name,
            "litellm_params": {
                "model": f"litellm_proxy/{model_name}",  # Prefix with litellm_proxy/
                "api_base": "os.environ/UPSTREAM_LITELLM_BASE_URL",
                "api_key": "os.environ/LITELLM_API_KEY"
            }
        })

    config = {
        "model_list": model_list,
        "litellm_settings": {
            "json_logs": True,
            "log_responses": True,
            "store_model_in_db": False,
            "telemetry": False
        }
    }

    return config


def display_models(models: list[dict]) -> None:
    """Display models in a readable format.

    Args:
        models: List of model dictionaries
    """
    print("\n" + "=" * 70)
    print("UPSTREAM MODELS")
    print("=" * 70)

    for i, model in enumerate(models, 1):
        model_name = model.get("id", "unknown")
        print(f"{i:3d}. {model_name}")

    print("=" * 70 + "\n")


def confirm_overwrite(config_path: Path) -> bool:
    """Ask user to confirm overwriting existing config.

    Args:
        config_path: Path to config file

    Returns:
        True if user confirms, False otherwise
    """
    if not config_path.exists():
        return True

    print(f"\n⚠️  WARNING: This will overwrite {config_path}")
    print("The current configuration will be backed up to:")
    print(f"   {config_path}.backup")

    while True:
        response = input("\nDo you want to continue? [y/N]: ").strip().lower()
        if response in ('y', 'yes'):
            return True
        elif response in ('n', 'no', ''):
            return False
        else:
            print("Please enter 'y' or 'n'")


def backup_config(config_path: Path) -> None:
    """Create backup of existing config file.

    Args:
        config_path: Path to config file
    """
    if not config_path.exists():
        return

    backup_path = config_path.with_suffix(config_path.suffix + ".backup")
    backup_path.write_bytes(config_path.read_bytes())
    print(f"✓ Backed up existing config to {backup_path}")


def write_config(config_path: Path, config: dict) -> None:
    """Write configuration to YAML file.

    Args:
        config_path: Path to write config
        config: Configuration dictionary
    """
    config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(config_path, 'w') as f:
        # Write header comment
        f.write("# LiteLLM Proxy Mode Configuration - Synced from Upstream\n")
        f.write("#\n")
        f.write("# This configuration was automatically generated by sync-upstream-models.py\n")
        f.write("# It forwards all requests to the upstream LiteLLM instance.\n")
        f.write("#\n")
        f.write("# Environment Variables Required:\n")
        f.write("#   UPSTREAM_LITELLM_BASE_URL - URL of upstream LiteLLM\n")
        f.write("#   LITELLM_API_KEY          - API key for upstream LiteLLM\n")
        f.write("#\n\n")

        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"✓ Wrote configuration to {config_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Sync LiteLLM models from upstream instance",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use environment variables from .env file
  # (set UPSTREAM_LITELLM_BASE_URL and LITELLM_API_KEY in .env)
  python scripts/sync-upstream-models.py

  # Specify via command line (overrides .env)
  python scripts/sync-upstream-models.py \\
    --upstream-url http://central-litellm:4000 \\
    --api-key sk-central-master-key

  # List models only (no write)
  python scripts/sync-upstream-models.py --list-only

  # Write to custom output file
  python scripts/sync-upstream-models.py \\
    --output services/litellm/custom-models.yaml

  # Skip confirmation prompt
  python scripts/sync-upstream-models.py -y
        """
    )

    parser.add_argument(
        '--upstream-url',
        help='Upstream LiteLLM base URL (default: UPSTREAM_LITELLM_BASE_URL env var)'
    )
    parser.add_argument(
        '--api-key',
        help='API key for upstream LiteLLM (default: LITELLM_API_KEY env var)'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=DEFAULT_MODELS_PATH,
        help=f'Output config file (default: {DEFAULT_MODELS_PATH})'
    )
    parser.add_argument(
        '--list-only',
        action='store_true',
        help='Only list models without updating config'
    )
    parser.add_argument(
        '--yes',
        '-y',
        action='store_true',
        help='Skip confirmation prompt'
    )

    args = parser.parse_args()

    # Get upstream URL
    upstream_url = args.upstream_url or os.getenv('UPSTREAM_LITELLM_BASE_URL')
    if not upstream_url:
        print("Error: Upstream URL not provided", file=sys.stderr)
        print("Set UPSTREAM_LITELLM_BASE_URL env var or use --upstream-url", file=sys.stderr)
        sys.exit(1)

    # Get API key
    api_key = args.api_key or os.getenv('LITELLM_API_KEY')
    if not api_key:
        print("Error: API key not provided", file=sys.stderr)
        print("Set LITELLM_API_KEY env var or use --api-key", file=sys.stderr)
        sys.exit(1)

    try:
        # Fetch models from upstream
        models = fetch_upstream_models(upstream_url, api_key)

        if not models:
            print("No models found from upstream", file=sys.stderr)
            sys.exit(1)

        # Display models
        display_models(models)

        # If list-only mode, exit here
        if args.list_only:
            print(f"Total: {len(models)} models")
            return

        # Ask for confirmation
        if not args.yes:
            if not confirm_overwrite(args.output):
                print("Aborted.")
                sys.exit(0)

        # Generate proxy config
        print("\nGenerating proxy configuration...")
        config = generate_proxy_config(upstream_url, models)

        # Backup existing config
        backup_config(args.output)

        # Write new config
        write_config(args.output, config)

        print(f"\n✓ Successfully synced {len(models)} models to {args.output}")
        print("\nYou can now start LiteLLM with:")
        print(f"  python scripts/litellm-helper.py start --config {args.output}")

    except requests.RequestException as e:
        print(f"Error fetching models from upstream: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
